name: Checkmarx
on:
  workflow_dispatch:
jobs:
  show-uid-and-gid:
    runs-on: ubuntu-latest

    steps:
       
    - name: Action User and UID
      shell: bash
      run: |
        echo User: $(whoami)
        echo UID: $(id -u)
        
    - name: Action Effective Groups
      shell: bash
      run: |
        echo Primary GID: $(id -g)
        echo Primary GID /etc/group entry: $(getent group $(id -g) )
        echo Effective GIDs: $(id -G)
          
        
        


         
